'use client'

import { ChangeEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { Bell, Database, Download, KeyRound, Lock, Moon, ScanFace, ShieldCheck, Sun, Trash2, Upload, WifiOff } from 'lucide-react'
import { db } from '@/lib/db/db'
import { seedDemoEntries } from '@/lib/db/seed'
import { createPinVault, registerBiometric } from '@/lib/crypto/vault'
import { migratePlaintextToVault } from '@/lib/repository/entries'
import { useSecurity } from '@/components/security/SecurityProvider'
import { createEncryptedBackup, restoreEncryptedBackup } from '@/lib/export/backup'

export function SettingsTools() {
  const {key,settings,refreshSettings,setUnlockedKey,lock}=useSecurity()
  const [message,setMessage]=useState(''); const [pin,setPin]=useState(''); const [backupPass,setBackupPass]=useState(''); const [theme,setTheme]=useState(settings?.theme||'system'); const [reminder,setReminder]=useState(settings?.reminderTime||'17:00'); const [reminderEnabled,setReminderEnabled]=useState(Boolean(settings?.reminderEnabled)); const [aiToken,setAiToken]=useState(settings?.aiAccessToken||''); const [autoLock,setAutoLock]=useState(settings?.security?.autoLockMin||5)
  useEffect(()=>{if(!settings)return;setTheme(settings.theme);setReminder(settings.reminderTime||'17:00');setReminderEnabled(Boolean(settings.reminderEnabled));setAiToken(settings.aiAccessToken||'');setAutoLock(settings.security?.autoLockMin||5)},[settings])
  async function saveGeneral(){ if(!settings)return; await db.settings.put({...settings,theme,reminderTime:reminder,reminderEnabled,aiAccessToken:aiToken.trim()||undefined,aiEnabled:Boolean(aiToken.trim()),security:settings.security?{...settings.security,autoLockMin:autoLock}:undefined,updatedAt:new Date().toISOString()}); localStorage.setItem('logkerja-theme',theme); const dark=theme==='dark'||(theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.classList.toggle('dark',dark); if(reminderEnabled&&'Notification' in window&&Notification.permission==='default')await Notification.requestPermission(); await refreshSettings();setMessage('Setelan tersimpan.') }
  async function enableVault(){ if(pin.length<6){setMessage('PIN minimal 6 karakter.');return} const vault=await createPinVault(pin,autoLock); await migratePlaintextToVault(vault.key); if(!settings)return; await db.settings.put({...settings,security:vault.config,updatedAt:new Date().toISOString()}); await setUnlockedKey(vault.key);await refreshSettings();setPin('');setMessage('Vault AES-GCM aktif. Data lama telah dimigrasikan.') }
  async function addBiometric(){ if(!key||!settings?.security){setMessage('Buka vault terlebih dahulu.');return} try{const bio=await registerBiometric(key);await db.settings.put({...settings,security:{...settings.security,biometric:bio},updatedAt:new Date().toISOString()});await refreshSettings();setMessage('Biometric WebAuthn PRF aktif.')}catch(err){setMessage(err instanceof Error?err.message:'Biometric tidak tersedia.')} }
  async function seed(){const count=await seedDemoEntries(key);setMessage(`${count} contoh catatan ditambahkan.`)}
  async function reset(){if(!confirm('Hapus seluruh data lokal LogKerja di perangkat ini?'))return; await Promise.all([db.entries.clear(),db.secureEntries.clear(),db.attachments.clear(),db.entryHistory.clear(),db.projects.clear(),db.tags.clear(),db.templates.clear(),db.settings.clear(),db.summaries.clear(),db.drafts.clear(),db.secureDrafts.clear(),db.focusSessions.clear(),db.integrationRuns.clear()]);sessionStorage.clear();setMessage('Semua data lokal dihapus. Muat ulang aplikasi untuk onboarding baru.')}
  async function backup(){try{await createEncryptedBackup(backupPass,key);setMessage('Backup terenkripsi berhasil dibuat. Simpan password backup dengan aman.')}catch(err){setMessage(err instanceof Error?err.message:'Backup gagal.')}}
  async function restore(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;try{const count=await restoreEncryptedBackup(file,backupPass);lock();await refreshSettings();setMessage(`${count} catatan dipulihkan. Vault dinonaktifkan setelah restore; aktifkan kembali PIN bila diinginkan.`)}catch(err){setMessage(err instanceof Error?err.message:'Restore gagal.')}finally{event.target.value=''}}
  return <div className="space-y-4">
    <section className="card p-5"><div className="flex items-center gap-2"><Sun size={18} className="text-indigo-500"/><h2 className="font-black">Tampilan & reminder</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><label className="label">Tema</label><select className="field" value={theme} onChange={e=>setTheme(e.target.value as any)}><option value="system">Ikuti sistem</option><option value="light">Terang</option><option value="dark">Gelap</option></select></div><div><label className="label">Auto-lock (menit)</label><select className="field" value={autoLock} onChange={e=>setAutoLock(Number(e.target.value))} disabled={!settings?.security}><option value={1}>1</option><option value={5}>5</option><option value={15}>15</option><option value={30}>30</option></select></div></div><label className="mt-4 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" className="h-5 w-5 accent-indigo-600" checked={reminderEnabled} onChange={e=>setReminderEnabled(e.target.checked)}/><Bell size={17}/> Reminder harian</label>{reminderEnabled&&<input type="time" className="field mt-3" value={reminder} onChange={e=>setReminder(e.target.value)}/>}<button className="btn-primary mt-4 w-full" onClick={()=>void saveGeneral()}>Simpan setelan</button></section>
    <section className="card p-5"><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-emerald-600"/><h2 className="font-black">Keamanan lokal</h2></div>{settings?.security?.enabled?<><div className="mt-3 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-300"><b>AES-GCM aktif.</b> PIN membungkus data-encryption-key; vault terkunci otomatis setelah idle.</div><div className="mt-3 grid gap-2 sm:grid-cols-2"><button className="btn-secondary" onClick={lock}><Lock size={17}/>Kunci sekarang</button><button className="btn-secondary" onClick={()=>void addBiometric()}><ScanFace size={17}/>{settings.security.biometric?'Daftar ulang biometric':'Aktifkan biometric'}</button></div></>:<><p className="mt-2 text-sm leading-6 text-slate-500">Aktifkan PIN untuk memigrasikan catatan dan attachment plaintext menjadi record terenkripsi.</p><div className="mt-3 flex gap-2"><input type="password" inputMode="numeric" className="field" placeholder="PIN minimal 6" value={pin} onChange={e=>setPin(e.target.value)}/><button className="btn-primary shrink-0" onClick={()=>void enableVault()}><KeyRound size={17}/>Aktifkan</button></div></>}</section>
    <section className="card p-5"><h2 className="font-black">AI server gate</h2><p className="mt-1 text-sm leading-6 text-slate-500">Masukkan token yang sama dengan secret <code>AI_ACCESS_TOKEN</code> di Cloudflare. Token ini tidak dibundel ke source app.</p><input className="field mt-3" type="password" value={aiToken} onChange={e=>setAiToken(e.target.value)} placeholder="Token personal untuk endpoint AI"/><button className="btn-secondary mt-3 w-full" onClick={()=>void saveGeneral()}>Simpan token AI di perangkat</button></section>
    <section className="card p-5"><div className="flex items-center gap-2"><Download size={18} className="text-indigo-500"/><h2 className="font-black">Emergency Backup</h2></div><p className="mt-1 text-sm leading-6 text-slate-500">Backup portable dienkripsi dengan password backup terpisah. Cocok untuk dipindah ke Drive/flashdisk/perangkat baru.</p><input className="field mt-3" type="password" value={backupPass} onChange={e=>setBackupPass(e.target.value)} placeholder="Password backup minimal 8 karakter"/><div className="mt-3 grid gap-2 sm:grid-cols-2"><button className="btn-secondary" onClick={()=>void backup()}><Download size={17}/>Buat .lkbackup</button><label className="btn-secondary cursor-pointer"><Upload size={17}/>Restore backup<input type="file" accept=".lkbackup,application/json" className="hidden" onChange={e=>void restore(e)}/></label></div></section>
    <section className="card p-5"><h2 className="font-black">Integrasi & data</h2><div className="mt-3 grid gap-2"><Link href="/integrations/" className="btn-secondary"><WifiOff size={17}/>Import Calendar / GitHub / CSV / JSON</Link><button onClick={()=>void seed()} className="btn-secondary"><Database size={18}/>Tambahkan 5 data demo</button><button onClick={()=>void reset()} className="btn-danger"><Trash2 size={18}/>Hapus semua data lokal</button></div></section>
    {message&&<p className="rounded-2xl bg-slate-900 p-4 text-center text-sm font-semibold text-white dark:bg-white dark:text-slate-900">{message}</p>}
  </div>
}
