'use client'

import { ChangeEvent, useState } from 'react'
import { CalendarDays, Download, FileJson, FileSpreadsheet, Github, Share2, UploadCloud } from 'lucide-react'
import { useEntries } from '@/hooks/useEntries'
import { useSecurity } from '@/components/security/SecurityProvider'
import { importCSV, importGithub, importICS, importJSON } from '@/lib/integrations/importers'
import { exportCsv, exportJson, exportMarkdown, exportPdf, shareMarkdown } from '@/lib/export/exporters'

export function IntegrationsHub(){
  const entries=useEntries(); const {key}=useSecurity(); const [github,setGithub]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false)
  async function handleFile(event:ChangeEvent<HTMLInputElement>,kind:'ics'|'csv'|'json'){const file=event.target.files?.[0];if(!file)return;setBusy(true);setMessage('');try{const text=await file.text();const count=kind==='ics'?await importICS(text,key):kind==='csv'?await importCSV(text,key):await importJSON(text,key);setMessage(`${count} item berhasil diimpor.`)}catch(err){setMessage(err instanceof Error?err.message:'Import gagal.')}finally{setBusy(false);event.target.value=''}}
  async function githubImport(){if(!github.trim())return;setBusy(true);setMessage('');try{const count=await importGithub(github.trim(),key);setMessage(`${count} aktivitas publik GitHub diimpor.`)}catch(err){setMessage(err instanceof Error?err.message:'GitHub import gagal.')}finally{setBusy(false)}}
  return <main className="app-shell"><header className="pt-2"><p className="eyebrow">INTEGRATIONS</p><h1 className="mt-1 text-3xl font-black">Import & Export Hub</h1><p className="mt-2 text-sm leading-6 text-slate-500">Utamakan file export/manual import agar diary tidak membutuhkan akses akun pihak ketiga terus-menerus.</p></header>
    <section className="card mt-5 p-5"><div className="flex items-center gap-2"><CalendarDays size={18} className="text-indigo-500"/><h2 className="font-black">Google Calendar / iCalendar</h2></div><p className="mt-1 text-sm text-slate-500">Export kalender sebagai <code>.ics</code>, lalu import. Event menjadi entry dan tetap lokal.</p><label className="btn-secondary mt-3 w-full cursor-pointer"><UploadCloud size={18}/>Import .ics<input type="file" accept=".ics,text/calendar" className="hidden" onChange={e=>void handleFile(e,'ics')}/></label></section>
    <section className="card mt-4 p-5"><div className="flex items-center gap-2"><Github size={18}/><h2 className="font-black">GitHub public activity</h2></div><p className="mt-1 text-sm text-slate-500">Tanpa token: membaca maksimal activity publik yang diberikan GitHub API. Cocok untuk developer/freelancer.</p><div className="mt-3 flex gap-2"><input className="field" value={github} onChange={e=>setGithub(e.target.value)} placeholder="GitHub username"/><button disabled={busy||!github.trim()} className="btn-primary shrink-0" onClick={()=>void githubImport()}>Import</button></div></section>
    <section className="card mt-4 p-5"><div className="flex items-center gap-2"><FileSpreadsheet size={18} className="text-emerald-600"/><h2 className="font-black">CSV / Notion CSV</h2></div><p className="mt-1 text-sm text-slate-500">Header yang dikenali: date/tanggal, activity/aktivitas/title, project/proyek, problem, solution, lesson, impact, mood, duration, tags.</p><label className="btn-secondary mt-3 w-full cursor-pointer"><UploadCloud size={18}/>Import .csv<input type="file" accept=".csv,text/csv" className="hidden" onChange={e=>void handleFile(e,'csv')}/></label></section>
    <section className="card mt-4 p-5"><div className="flex items-center gap-2"><FileJson size={18} className="text-amber-600"/><h2 className="font-black">JSON / Trello</h2></div><p className="mt-1 text-sm text-slate-500">Menerima array entry LogKerja, object Trello dengan <code>cards[]</code>, atau file JSON per-channel dari export Slack.</p><label className="btn-secondary mt-3 w-full cursor-pointer"><UploadCloud size={18}/>Import .json<input type="file" accept=".json,application/json" className="hidden" onChange={e=>void handleFile(e,'json')}/></label></section>
    <section className="card mt-4 p-5"><div className="flex items-center gap-2"><Download size={18} className="text-indigo-500"/><h2 className="font-black">Export laporan</h2></div><p className="mt-1 text-sm text-slate-500">Export ini berisi plaintext yang Anda pilih. Simpan di tempat aman.</p><div className="mt-3 grid grid-cols-2 gap-2"><button className="btn-secondary" onClick={()=>exportMarkdown(entries)}>Markdown</button><button className="btn-secondary" onClick={()=>exportCsv(entries)}>CSV</button><button className="btn-secondary" onClick={()=>exportJson(entries)}>JSON</button><button className="btn-secondary" onClick={()=>void exportPdf(entries)}>PDF</button><button className="btn-secondary col-span-2" onClick={()=>void shareMarkdown(entries)}><Share2 size={16}/>Share via Android</button></div></section>
    {busy&&<p className="mt-4 text-center text-sm font-semibold text-indigo-600">Memproses…</p>}{message&&<p className="mt-4 rounded-2xl bg-slate-900 p-4 text-center text-sm font-semibold text-white dark:bg-white dark:text-slate-900">{message}</p>}
  </main>
}
