'use client'

import { useEffect, useMemo, useState } from 'react'
import { Brain, Download, MessageCircleQuestion, Sparkles, WifiOff } from 'lucide-react'
import { useLiveQuery } from 'dexie-react-hooks'
import { db } from '@/lib/db/db'
import { useEntries } from '@/hooks/useEntries'
import { useSecurity } from '@/components/security/SecurityProvider'
import { dailyPrompts, offlineBrag, offlineReviewPrep, offlineSummary, offlineWeeklyLetter, problemPatterns } from '@/lib/ai/offline'
import { runAI, sanitizeEntries } from '@/lib/ai/client'
import { dateRange, filterRange } from '@/lib/stats/stats'
import type { AIRequestPayload, SummaryPeriod } from '@/types'
import { WhisperPanel } from './WhisperPanel'

const actions:Array<{mode:AIRequestPayload['mode'];label:string;desc:string}>=[
  {mode:'weekly',label:'Weekly Summary',desc:'Progres, hambatan, pelajaran, action item'},
  {mode:'monthly',label:'Monthly Review',desc:'Highlight, proyek, skill, risiko, prioritas'},
  {mode:'brag',label:'Brag Document',desc:'Bukti pencapaian menjadi format STAR'},
  {mode:'patterns',label:'Problem Pattern',desc:'Masalah berulang + solusi sistemik'},
  {mode:'weekly-letter',label:'Letter to Self',desc:'Surat reflektif mingguan'},
  {mode:'review-prep',label:'Review Prep',desc:'Bahan performance review'}
]
function periodFor(mode:AIRequestPayload['mode']):SummaryPeriod {if(mode==='brag')return'brag';if(mode==='review-prep')return'review';if(mode==='weekly-letter')return'letter';if(mode==='patterns')return'patterns';return mode==='monthly'?'monthly':'weekly'}
function downloadText(text:string,name:string){const url=URL.createObjectURL(new Blob([text],{type:'text/markdown'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

export function InsightsStudio(){
  const entries=useEntries(); const {settings}=useSecurity(); const recentSummaries=useLiveQuery(()=>db.summaries.orderBy('generatedAt').reverse().limit(5).toArray(),[],[]); const initial=dateRange(7); const [from,setFrom]=useState(initial.start); const [to,setTo]=useState(initial.end); const [result,setResult]=useState(''); const [title,setTitle]=useState(''); const [source,setSource]=useState<'ai'|'offline'>('offline'); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [question,setQuestion]=useState('Apa masalah terbesar pada periode ini?'); const [online,setOnline]=useState(true); const prompts=useMemo(()=>dailyPrompts(),[]); const selected=useMemo(()=>filterRange(entries,from,to),[entries,from,to])
  useEffect(()=>{const sync=()=>setOnline(navigator.onLine);sync();window.addEventListener('online',sync);window.addEventListener('offline',sync);return()=>{window.removeEventListener('online',sync);window.removeEventListener('offline',sync)}},[])
  async function generate(mode:AIRequestPayload['mode']){setBusy(true);setError(''); const label=actions.find(a=>a.mode===mode)?.label||(mode==='daily-prompts'?'Daily Prompts AI':'AI Q&A');setTitle(label);try{let text:string;let used:'ai'|'offline'='offline';if(settings?.aiEnabled&&settings.aiAccessToken&&online){const res=await runAI({mode,entries:sanitizeEntries(selected),question:mode==='qa'?question:undefined,locale:settings.language},settings.aiAccessToken);text=res.text;used='ai'}else{if(mode==='brag')text=offlineBrag(selected);else if(mode==='patterns')text=problemPatterns(selected);else if(mode==='daily-prompts')text=dailyPrompts().map((p,i)=>`${i+1}. ${p}`).join('\n');else if(mode==='weekly-letter')text=offlineWeeklyLetter(selected);else if(mode==='review-prep')text=offlineReviewPrep(selected);else if(mode==='qa')text=`Mode Q&A memerlukan AI online.\n\nFallback offline tersedia untuk ringkasan, brag document, pattern detector, weekly letter, dan review prep.`;else text=offlineSummary(selected)}setResult(text);setSource(used);if(!['qa','daily-prompts','whisper-structure'].includes(mode)){await db.summaries.put({id:crypto.randomUUID(),period:periodFor(mode),rangeStart:from,rangeEnd:to,title:label,content:text,source:used,generatedAt:new Date().toISOString()})}}catch(err){setError(err instanceof Error?err.message:'Analisis gagal.')}finally{setBusy(false)}}
  return <main className="app-shell"><header className="pt-2"><p className="eyebrow">INSIGHTS</p><h1 className="mt-1 text-3xl font-black">Reflection Studio</h1><p className="mt-2 text-sm leading-6 text-slate-500">Analisis lokal tetap tersedia offline. AI online hanya menerima teks entry yang dipilih setelah Anda menekan tombol.</p></header>
    <section className="card mt-5 p-5"><div className="flex items-center gap-2"><Sparkles size={18} className="text-violet-500"/><h2 className="font-black">Daily Prompt</h2></div><div className="mt-3 space-y-2">{prompts.map((p,i)=><div key={p} className="rounded-2xl bg-violet-50 p-3 text-sm font-semibold text-violet-900 dark:bg-violet-950/30 dark:text-violet-200"><span className="mr-2 text-violet-400">0{i+1}</span>{p}</div>)}</div><button disabled={busy} onClick={()=>void generate('daily-prompts')} className="btn-secondary mt-3 w-full">Buat 3 pertanyaan versi AI</button></section>
    <section className="card mt-4 p-5"><h2 className="font-black">Periode analisis</h2><div className="mt-3 grid grid-cols-2 gap-3"><input className="field" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="field" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div><p className="mt-2 text-xs font-semibold text-slate-500">{selected.length} entry akan digunakan · attachment tidak pernah dikirim ke AI.</p></section>
    <section className="mt-4 grid gap-3 sm:grid-cols-2">{actions.map(a=><button key={a.mode} disabled={busy} onClick={()=>void generate(a.mode)} className="card p-4 text-left transition active:scale-[.99]"><div className="flex items-center justify-between"><h3 className="font-black">{a.label}</h3>{settings?.aiEnabled&&online?<Brain size={18} className="text-indigo-500"/>:<WifiOff size={18} className="text-slate-400"/>}</div><p className="mt-1 text-xs leading-5 text-slate-500">{a.desc}</p></button>)}</section>
    <section className="card mt-4 p-5"><div className="flex items-center gap-2"><MessageCircleQuestion size={18} className="text-indigo-500"/><h2 className="font-black">Tanya Diary</h2></div><textarea className="field mt-3" rows={3} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Apa masalah terbesar bulan ini?"/><button disabled={busy||!question.trim()} className="btn-secondary mt-3 w-full" onClick={()=>void generate('qa')}>Tanya berdasarkan {selected.length} entry</button></section>
    <WhisperPanel/>
    {recentSummaries.length>0&&<section className="card mt-4 p-5"><h2 className="font-black">Riwayat output</h2><p className="mt-1 text-xs text-slate-500">Termasuk weekly recap otomatis yang dibuat lokal saat aplikasi dibuka pada hari Senin.</p><div className="mt-3 space-y-2">{recentSummaries.map(s=><button key={s.id} className="w-full rounded-2xl bg-slate-50 p-3 text-left dark:bg-slate-800" onClick={()=>{setTitle(s.title);setResult(s.content);setSource(s.source)}}><div className="flex items-center justify-between gap-2"><span className="text-sm font-bold">{s.title}</span><span className="text-[10px] font-bold uppercase text-slate-400">{s.source}</span></div><p className="mt-1 text-xs text-slate-500">{s.rangeStart} — {s.rangeEnd}</p></button>)}</div></section>}
    {!settings?.aiEnabled&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-800 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200"><b>AI online belum aktif.</b> Isi <code>OPENAI_API_KEY</code> + <code>AI_ACCESS_TOKEN</code> di Cloudflare, lalu simpan access token yang sama di Settings. Sampai saat itu, generator memakai fallback lokal.</div>}
    {error&&<p className="mt-4 rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</p>}
    {busy&&<div className="card mt-4 h-40 animate-pulse bg-slate-100 dark:bg-slate-800"/>}
    {result&&!busy&&<section className="card mt-4 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-4 dark:border-slate-800"><div><p className="eyebrow">{source==='ai'?'AI ONLINE':'OFFLINE ENGINE'}</p><h2 className="font-black">{title}</h2></div><button className="btn-secondary !min-h-9 !px-3" onClick={()=>downloadText(result,`logkerja-${title.toLowerCase().replace(/\s+/g,'-')}.md`)}><Download size={15}/></button></div><pre className="whitespace-pre-wrap break-words p-5 font-sans text-sm leading-7 text-slate-700 dark:text-slate-200">{result}</pre></section>}
  </main>
}
