import { createEntry } from '@/lib/repository/entries'
import { db } from '@/lib/db/db'
import type { Mood } from '@/types'

type Input={date:string;activity:string;project?:string;client?:string;problem?:string;solution?:string;lesson?:string;impact?:string;mood?:Mood;durationMin?:number;tags?:string[];skills?:string[];isAchievement?:boolean}
function dateKey(value?:string){if(!value)return new Date().toISOString().slice(0,10);const normalized=value.length===8&&/^\d{8}$/.test(value)?`${value.slice(0,4)}-${value.slice(4,6)}-${value.slice(6,8)}`:value;const d=new Date(normalized);return Number.isNaN(d.getTime())?new Date().toISOString().slice(0,10):d.toISOString().slice(0,10)}
async function addMany(rows:Input[],key:CryptoKey|null,provider:'calendar'|'github'|'csv'|'json'|'trello'|'notion'|'slack'){let count=0;for(const r of rows){if(!r.activity?.trim())continue;await createEntry({date:dateKey(r.date),activity:r.activity.trim(),project:r.project,client:r.client,problem:r.problem,solution:r.solution,lesson:r.lesson,impact:r.impact,mood:r.mood||3,durationMin:r.durationMin,tags:r.tags||[provider],skills:r.skills,isAchievement:r.isAchievement,archived:false,syncedAt:null,files:[]},key);count++}await db.integrationRuns.add({id:crypto.randomUUID(),provider,imported:count,createdAt:new Date().toISOString()});return count}

export async function importICS(text:string,key:CryptoKey|null){
  const unfolded=text.replace(/\r?\n[ \t]/g,'');const blocks=unfolded.split('BEGIN:VEVENT').slice(1).map(x=>x.split('END:VEVENT')[0]);const rows:Input[]=[]
  const get=(b:string,n:string)=>{const line=b.split(/\r?\n/).find(l=>l.startsWith(`${n}:`)||l.startsWith(`${n};`));return line?line.slice(line.indexOf(':')+1).replace(/\\n/g,'\n').replace(/\\,/g,',').trim():''}
  for(const b of blocks){const summary=get(b,'SUMMARY');if(!summary)continue;rows.push({date:dateKey(get(b,'DTSTART')),activity:`Calendar: ${summary}`,lesson:get(b,'DESCRIPTION')||undefined,project:'Calendar',tags:['calendar','import']})}
  return addMany(rows,key,'calendar')
}
function parseCSV(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.length))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(x=>x.length))rows.push(row);return rows}
export async function importCSV(text:string,key:CryptoKey|null){const matrix=parseCSV(text);if(matrix.length<2)return 0;const headers=matrix[0].map(h=>h.trim().toLowerCase());const idx=(...names:string[])=>headers.findIndex(h=>names.includes(h));const rows:Input[]=matrix.slice(1).map(r=>({date:dateKey(r[idx('date','tanggal')]),activity:r[idx('activity','aktivitas','name','title','task')]||'',project:r[idx('project','proyek','board')]||undefined,client:r[idx('client','klien','unit')]||undefined,problem:r[idx('problem','masalah')]||undefined,solution:r[idx('solution','solusi')]||undefined,lesson:r[idx('lesson','pelajaran')]||undefined,impact:r[idx('impact','dampak','result')]||undefined,mood:(Number(r[idx('mood')])||3) as Mood,durationMin:Number(r[idx('durationmin','duration','durasi')])||undefined,tags:(r[idx('tags','tag')]||'csv,import').split(/[|;]/).map(x=>x.trim()).filter(Boolean)}));return addMany(rows,key,'csv')}
export async function importJSON(text:string,key:CryptoKey|null){const data=JSON.parse(text);let rows:Input[]=[];let provider:'json'|'trello'|'notion'|'slack'='json';if(Array.isArray(data)&&data.length&&typeof data[0]?.text==='string'&&data[0]?.ts){provider='slack';rows=data.map((x:any)=>({date:dateKey(new Date(Number(String(x.ts).split('.')[0])*1000).toISOString()),activity:x.text||'',project:'Slack',tags:['slack','import']}))}else if(Array.isArray(data)){rows=data.map((x:any)=>({date:dateKey(x.date||x.createdAt),activity:x.activity||x.name||x.title||'',project:x.project,client:x.client,problem:x.problem,solution:x.solution,lesson:x.lesson,impact:x.impact,mood:(Number(x.mood)||3) as Mood,durationMin:Number(x.durationMin)||undefined,tags:Array.isArray(x.tags)?x.tags:['json','import'],skills:Array.isArray(x.skills)?x.skills:undefined,isAchievement:Boolean(x.isAchievement)}))}else if(Array.isArray(data?.cards)){provider='trello';rows=data.cards.map((c:any)=>({date:dateKey(c.dateLastActivity),activity:c.name||'',lesson:c.desc||undefined,project:data.name||'Trello',tags:['trello','import'],isAchievement:undefined} as any))}else if(Array.isArray(data?.results)){provider='notion';rows=data.results.map((x:any)=>({date:dateKey(x.date||x.created_time),activity:x.name||x.title||x.activity||'',project:x.project||'Notion',tags:['notion','import']}))}else throw new Error('JSON tidak dikenali. Gunakan array entry atau export Trello/Notion yang didukung.');return addMany(rows,key,provider)}

export async function importGithub(username:string,key:CryptoKey|null){
  const response=await fetch(`https://api.github.com/users/${encodeURIComponent(username)}/events?per_page=100`,{headers:{Accept:'application/vnd.github+json'}});if(!response.ok)throw new Error(`GitHub API gagal (${response.status}). Hanya public activity yang dapat diimpor tanpa token.`);const events:any[]=await response.json();const rows:Input[]=[]
  for(const e of events){const repo=e.repo?.name||'GitHub';let activity='';if(e.type==='PushEvent')activity=`Push ${e.payload?.size||0} commit ke ${repo}`;else if(e.type==='PullRequestEvent')activity=`${e.payload?.action||'Update'} pull request di ${repo}: ${e.payload?.pull_request?.title||''}`;else if(e.type==='IssuesEvent')activity=`${e.payload?.action||'Update'} issue di ${repo}: ${e.payload?.issue?.title||''}`;else if(e.type==='CreateEvent')activity=`Membuat ${e.payload?.ref_type||'resource'} ${e.payload?.ref||''} di ${repo}`;else continue;rows.push({date:dateKey(e.created_at),activity,project:repo,tags:['github','import'],skills:['git']})}
  return addMany(rows,key,'github')
}
