'use client'

import { Activity, Award, BarChart3, BrainCircuit, Clock3, TrendingUp } from 'lucide-react'
import { useEntries } from '@/hooks/useEntries'
import { heatmap, moodOutputCorrelation, moodSeries, projectMinutes, skillCounts } from '@/lib/analytics/metrics'

function MoodChart({data}:{data:ReturnType<typeof moodSeries>}){if(data.length<2)return <p className="text-sm text-slate-500">Butuh minimal 2 hari data.</p>;const w=500,h=150,p=18;const points=data.slice(-30).map((d,i)=>{const x=p+i*((w-2*p)/Math.max(1,Math.min(29,data.slice(-30).length-1)));const y=h-p-((d.mood-1)/4)*(h-2*p);return `${x},${y}`}).join(' ');return <svg viewBox={`0 0 ${w} ${h}`} className="h-40 w-full" role="img" aria-label="Tren mood"><line x1={p} x2={w-p} y1={h-p} y2={h-p} stroke="currentColor" opacity=".15"/><polyline points={points} fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round" className="text-indigo-500"/>{data.slice(-30).map((d,i)=>{const x=p+i*((w-2*p)/Math.max(1,Math.min(29,data.slice(-30).length-1)));const y=h-p-((d.mood-1)/4)*(h-2*p);return <circle key={d.date} cx={x} cy={y} r="4" fill="currentColor" className="text-indigo-600"><title>{d.date}: {d.mood.toFixed(1)}</title></circle>})}</svg>}
function correlationLabel(r:number|null){if(r===null)return 'Belum cukup data';const abs=Math.abs(r);const strength=abs<.2?'sangat lemah':abs<.4?'lemah':abs<.6?'sedang':abs<.8?'kuat':'sangat kuat';return `${r>0?'Positif':r<0?'Negatif':'Netral'} · ${strength} (r=${r.toFixed(2)})`}
export function AnalyticsDashboard(){const entries=useEntries().filter(e=>!e.archived);const projects=projectMinutes(entries);const max=Math.max(1,...projects.map(x=>x[1]));const skills=skillCounts(entries).slice(0,12);const mood=moodSeries(entries);const heat=heatmap(entries);const corr=moodOutputCorrelation(entries);const achievements=entries.filter(e=>e.isAchievement).sort((a,b)=>b.date.localeCompare(a.date));const totalMin=entries.reduce((s,e)=>s+(e.durationMin||0),0);const avgMood=entries.length?entries.reduce((s,e)=>s+e.mood,0)/entries.length:0
return <main className="app-shell"><header className="pt-2"><p className="eyebrow">ANALYTICS</p><h1 className="mt-1 text-3xl font-black">Work Intelligence</h1><p className="mt-2 text-sm leading-6 text-slate-500">Semua metrik dihitung lokal dari IndexedDB. Korelasi adalah pola statistik, bukan bukti sebab-akibat.</p></header>
<div className="mt-5 grid grid-cols-3 gap-3"><div className="card p-4"><Clock3 size={20} className="text-indigo-500"/><p className="mt-2 text-2xl font-black">{(totalMin/60).toFixed(1)}h</p><p className="text-xs text-slate-500">durasi tercatat</p></div><div className="card p-4"><Activity size={20} className="text-emerald-500"/><p className="mt-2 text-2xl font-black">{avgMood.toFixed(1)}</p><p className="text-xs text-slate-500">mood rata-rata</p></div><div className="card p-4"><Award size={20} className="text-amber-500"/><p className="mt-2 text-2xl font-black">{achievements.length}</p><p className="text-xs text-slate-500">pencapaian</p></div></div>
<section className="card mt-4 p-5"><div className="flex items-center gap-2"><BarChart3 size={18} className="text-indigo-500"/><h2 className="font-black">Waktu per proyek</h2></div><div className="mt-4 space-y-3">{projects.length?projects.slice(0,8).map(([name,min])=><div key={name}><div className="mb-1 flex justify-between text-xs font-semibold"><span>{name}</span><span className="text-slate-400">{Math.round(min/60*10)/10}h</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-indigo-500" style={{width:`${Math.max(3,min/max*100)}%`}}/></div></div>):<p className="text-sm text-slate-500">Isi durasi pada entry agar chart muncul.</p>}</div></section>
<section className="card mt-4 p-5"><div className="flex items-center gap-2"><TrendingUp size={18} className="text-indigo-500"/><h2 className="font-black">Mood trend</h2></div><MoodChart data={mood}/></section>
<section className="card mt-4 p-5"><div className="flex items-center gap-2"><BrainCircuit size={18} className="text-violet-500"/><h2 className="font-black">Mood vs output proxy</h2></div><p className="mt-3 text-2xl font-black">{correlationLabel(corr)}</p><p className="mt-2 text-xs leading-5 text-slate-500">Proxy output = jumlah entry per hari. Jangan menyamakannya dengan produktivitas nyata; gunakan hanya sebagai sinyal untuk refleksi.</p></section>
<section className="card mt-4 p-5"><h2 className="font-black">Activity heatmap · 12 minggu</h2><div className="mt-4 grid grid-cols-14 gap-1">{heat.map(d=><div key={d.date} title={`${d.date}: ${d.count} entry`} className={`aspect-square rounded-[4px] ${d.count===0?'bg-slate-100 dark:bg-slate-800':d.count===1?'bg-indigo-200 dark:bg-indigo-900':d.count===2?'bg-indigo-400':'bg-indigo-600'}`}/>)}</div></section>
<section className="card mt-4 p-5"><h2 className="font-black">Skill Tracker</h2><div className="mt-3 flex flex-wrap gap-2">{skills.length?skills.map(([s,n])=><span key={s} className="rounded-full bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-700 dark:bg-emerald-950/30 dark:text-emerald-300">{s} · {n}</span>):<p className="text-sm text-slate-500">Tambahkan skill di Quick Capture atau edit entry.</p>}</div></section>
<section className="card mt-4 p-5"><h2 className="font-black">Career Timeline</h2><div className="mt-4 space-y-4">{achievements.length?achievements.slice(0,12).map(e=><div key={e.id} className="relative border-l-2 border-indigo-200 pl-4 dark:border-indigo-900"><span className="absolute -left-[6px] top-1 h-2.5 w-2.5 rounded-full bg-indigo-600"/><p className="text-xs font-bold text-slate-400">{e.date} · {e.project||'Tanpa proyek'}</p><p className="mt-1 font-semibold">{e.activity}</p>{e.impact&&<p className="mt-1 text-sm text-emerald-700 dark:text-emerald-300">Dampak: {e.impact}</p>}</div>):<p className="text-sm text-slate-500">Tandai entry sebagai “pencapaian penting” untuk membangun timeline karier.</p>}</div></section>
</main>}
