import Link from 'next/link'
import { BookOpenCheck, Brain, Download, LockKeyhole, NotebookPen, Plus, Smartphone, UploadCloud } from 'lucide-react'
const steps=[
  ['1. Install PWA',Smartphone,'Buka URL Cloudflare di Chrome Android → menu ⋮ → Install app / Add to Home screen. Setelah service worker aktif, fitur inti tetap jalan offline.'],
  ['2. Catat cepat',Plus,'Tekan tombol + di bawah. Pilih jenis pekerjaan, isi Aktivitas dan Mood, lalu Simpan. Tambah/ubah jenis pekerjaan lewat menu Pekerjaan. Semua log tetap masuk Global. Proyek dan detail lainnya opsional.'],
  ['3. Cari bukti kerja',BookOpenCheck,'Timeline dapat dicari dan difilter berdasarkan proyek, mood, tanggal, dan pencapaian. Buka card untuk edit, duplikat, arsip, hapus, download attachment, atau melihat riwayat perubahan.'],
  ['Note bebas',NotebookPen,'Tab Note terpisah dari log. Buat Note per jenis pekerjaan; isi teks, daftar, gambar, kanvas, rekaman audio, dan peta pikiran bercabang. Teks daftar panjang turun otomatis ke baris berikutnya. Tekan Simpan setelah mengetik. Centang daftar langsung menyimpan tanggal dan jamnya; riwayat centang bisa dihapus per kejadian atau seluruhnya. Pin, Arsip, Riwayat versi, dan Sampah 30 hari tersedia di editor.'],
  ['4. Kunci diary',LockKeyhole,'Settings → aktifkan PIN. Catatan dan attachment lama dimigrasikan ke AES-GCM. Biometric menggunakan WebAuthn PRF jika authenticator mendukungnya; PIN selalu menjadi fallback.'],
  ['5. Gunakan AI dengan sadar',Brain,'Insights → pilih periode → tekan jenis analisis. Hanya teks entry pada periode tersebut yang dikirim; attachment tidak ikut. Tanpa internet/AI, fallback lokal tetap bekerja.'],
  ['6. Backup sebelum berisiko',Download,'Settings → Emergency Backup → masukkan password backup minimal 8 karakter → buat file .lkbackup. Backup memuat log dan Note beserta lampiran dan riwayatnya. Simpan file dan password; restore mengganti data lokal saat ini.'],
  ['7. Import sumber lain',UploadCloud,'Integrations mendukung .ics kalender, public GitHub activity, CSV, JSON/Trello, plus export Markdown/CSV/JSON/PDF.']
] as const
export default function HelpPage(){return <main className="app-shell"><header className="pt-2"><p className="eyebrow">MANUAL</p><h1 className="mt-1 text-3xl font-black">Cara memakai LogKerja</h1><p className="mt-2 text-sm leading-6 text-slate-500">Panduan ini juga tersedia offline setelah PWA pernah dimuat.</p></header><section className="mt-5 space-y-3">{steps.map(([title,Icon,text])=><article key={title} className="card p-5"><div className="flex gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-indigo-50 text-indigo-600 dark:bg-indigo-950"><Icon size={20}/></div><div><h2 className="font-black">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></div></div></article>)}</section><section className="card mt-4 p-5"><h2 className="font-black">Batasan reminder</h2><p className="mt-2 text-sm leading-6 text-slate-500">Versi Cloudflare Pages ini memberi reminder lokal saat PWA aktif. Android/browser dapat menghentikan timer saat aplikasi benar-benar tertutup. True scheduled push membutuhkan backend push + scheduler; sengaja tidak saya pura-purakan sebagai fitur yang pasti berjalan.</p></section><section className="card mt-4 p-5"><h2 className="font-black">Aturan privacy</h2><p className="mt-2 text-sm leading-6 text-slate-500">IndexedDB adalah sumber data utama. AI hanya dipanggil atas tindakan Anda. Export laporan menghasilkan plaintext, sedangkan Emergency Backup memakai enkripsi terpisah.</p></section><Link href="/" className="btn-primary mt-5 w-full">Kembali ke Home</Link></main>}
